name: example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:

      - name: step1
        uses: actions/checkout@v3

      - name : step2
        run: ls

      - name : step3
        run: kibot --quick-start

      - name: step4
        uses: actions/upload-artifact@v3
        with:
          name: Generated
          path: Generated
