# name
name: kicad-runner

# on
on:
  # on
  push:
    branches: [ "main" ]
    paths:
      - '**.kicad_pro'
      - '**.kicad_pcb'
      - '**.kicad_sch'  
  # on
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.kicad_pro'
      - '**.kicad_pcb'
      - '**.kicad_sch'
# jobs
jobs:
  kicad-runner:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:
      # step 1
      - name: Checkout Repo
        uses: actions/checkout@v3
      # step 2
      - name : Generate Outputs
        run: kibot --quick-start
      # step 3
      - name: Upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "Generated"
          target: ~/
      # step 4
      - name: Adding Markdown
        run: |
          echo "### PCB Release Files Generated! :rocket:" >> $GITHUB_STEP_SUMMARY
