name: kicad-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name : generate
        run: kibot

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: Generated
          path: Generated
