name: kicad-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  kicad-runner:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name : Generate
        run: kibot --quick-start

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Generated Data
          path: Generated

      - name: Image
        uses: actions/upload-artifact@v3
        with:
          name: kicad-test-3D_top30deg.png
          path: Generated/3D/kicad-test-3D_top30deg.png

      - name: Image upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "Generated/3D/kicad-test-3D_top30deg.png"
          target: ~/kicad-test-3D_top30deg.png

      - name: Adding markdown
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "![pcb](Generated/3D/kicad-test-3D_top30deg.png)" >> $GITHUB_STEP_SUMMARY
